---
title: "Integrating mutation breeding and genomic selection in Taro"
author: "Chinedozi and Dr Onyeka"
date: "`r Sys.Date()`"
output: word_document
---

#Understanding mutation breeding in crops or incorporating mutation breeding with genomic prediction in taro
Taro is one of the important aroids in Nigeria and other tropical countries. It is food for – people in the world (). The world production of the crop for 2023 to 2024 () with Nigeria being the top producer of the crop ().  
All parts of the taro are useful as food for both humans and animal. The young leaves are edible and so are the corms and cormels. 
Growing conditions of taro

The botany of taro 
Taro is usually cultivated vegetatively using  the corms and the cormels this is because of the firstly most taro varieties do not flow and or have produce poor seeds and secondly the onset of disease intercepts the time of flower maturation leading to the death of most of the plant hence lack of seeds available for the next planting season. 
Taro breeders are looking for ways to overcome the problem of seed availability and have employed method such as staggering yhe planting time to escape disease the peak of disease outbreak. 
Mutation breeding is one ,method that breeders can employ to increase genetic diversity of taro. We have to understand what mutation is before understanding what mutation breeding is.

What is mutation

